INSERT INTO guess_answer(name, difficulty) VALUES ('Marilyn Monroe', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('Abraham Lincoln', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('Nelson Mandela', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('John F. Kennedy', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('Martin Luther King', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('Queen Elizabeth II', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('Winston Churchill', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('Donald Trump', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('Bill Gates', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('Muhammad Ali', 0);
INSERT INTO guess_answer(name, difficulty) VALUES ('Mahatma Gandhi', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Margaret Thatcher', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Mother Teresa', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Christopher Columbus', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Charles Darwin', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Elvis Presley', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Albert Einstein', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Paul McCartney', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Queen Victoria', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Pope Francis', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Jawaharlal Nehru', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Leonardo da Vinci', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Vincent Van Gogh', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Franklin D. Roosevelt', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Pope John Paul II', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Thomas Edison', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Rosa Parks', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Lyndon Johnson', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Ludwig Beethoven', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Oprah Winfrey', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Indira Gandhi', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Eva Peron', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Benazir Bhutto', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('George Orwell', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Desmond Tutu', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Dalai Lama', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Walt Disney', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Neil Armstrong', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Peter Sellers', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Barack Obama', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Malcolm 1', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('J.K.Rowling', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Richard Branson', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Pele', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Angelina Jolie', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Jesse Owens', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('John Lennon', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Henry Ford', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Haile Selassie', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Joseph Stalin', 1);
INSERT INTO guess_answer(name, difficulty) VALUES ('Lord Baden Powell', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Michael Jordon', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('George Bush Jnr', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Vladimir Lenin', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Ingrid Bergman', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Fidel Castro', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Leo Tolstoy', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Greta Thunberg', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Pablo Picasso', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Oscar Wilde', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Coco Chanel', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Charles de Gaulle', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Amelia Earhart', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('John M Keynes', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Louis Pasteur', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Mikhail Gorbachev', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Plato', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Adolf Hitler', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Sting', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Mary Magdalene', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Alfred Hitchcock', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Michael Jackson', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Madonna', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Mata Hari', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Cleopatra', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Grace Kelly', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Steve Jobs', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Ronald Reagan', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Lionel Messi', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Babe Ruth', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Bob Geldof', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Leon Trotsky', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Roger Federer', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Sigmund Freud', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Woodrow Wilson', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Mao Zedong', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Katherine Hepburn', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Audrey Hepburn', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('David Beckham', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Tiger Woods', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Usain Bolt', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Carl Lewis', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Prince Charles', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Jacqueline Kennedy Onassis', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('C.S. Lewis', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Billie Holiday', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('J.R.R. Tolkien', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Billie Jean King', 2);
INSERT INTO guess_answer(name, difficulty) VALUES ('Anne Frank', 2);
