# Generated by Django 2.2.7 on 2019-11-24 13:54

import django_enumfield.db.fields
from django.db import migrations

import guess.models


class Migration(migrations.Migration):
    dependencies = [
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='difficulty',
            field=django_enumfield.db.fields.EnumField(default=0, enum=guess.models.Difficulty),
            preserve_default=False,
        ),
    ]
